name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    environment: prod

    env:
      AMBIENTE: ${{ vars.AMBIENTE }}
      PROD_DOMINIO: ${{ vars.PROD_DOMINIO }}
      PROD_DOMINIO_LOGIN: ${{ vars.PROD_DOMINIO_LOGIN }}
      PROD_EMAIL: ${{ vars.PROD_EMAIL }}
      PROD_SENHA: ${{ vars.PROD_SENHA }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Bdd gen
        run: npx bddgen

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-html-report
          path: Reports/html-report/
          retention-days: 30

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results
          path: Reports/allure-results/
          retention-days: 30